/var/log/bigdata-simulator*.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    sharedscripts
    postrotate
        pm2 reloadLogs bigdata-simulator > /dev/null 2>&1 || true
    endscript
}
